# Generated by Django 3.1.7 on 2022-01-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0003_auto_20220131_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='last_vaccination_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
