# Generated by Django 3.1.7 on 2022-01-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0004_dog_last_vaccination_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='chipped',
            field=models.BooleanField(default=False),
        ),
    ]
