# Generated by Django 3.1.7 on 2022-01-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0005_dog_chipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='', max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('date_completed', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='chipped',
            new_name='microchipped',
        ),
        migrations.AddField(
            model_name='dog',
            name='tasks',
            field=models.ManyToManyField(default='', related_name='remaining_tasks', to='paws.Task'),
        ),
    ]
