# Generated by Django 3.1.7 on 2022-02-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0007_auto_20220201_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
