# Generated by Django 3.1.7 on 2022-02-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0010_auto_20220202_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='dog',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
