# Generated by Django 3.1.7 on 2022-02-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0011_auto_20220203_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='food',
            name='age_group',
            field=models.CharField(choices=[('A', 'Adult'), ('P', 'Puppy')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='food',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
